import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  env: {  NEXT_PUBLIC_GEMINI_API_KEY: process.env.NEXT_PUBLIC_GEMINI_API_KEY, NEXT_PUBLIC_GEMINI_PROJECT_ID: process.env.NEXT_PUBLIC_GEMINI_PROJECT_ID, NEXT_PUBLIC_FIREBASE_PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    GOOGLE_CLIENT_EMAIL: process.env.GOOGLE_CLIENT_EMAIL, GOOGLE_PRIVATE_KEY: process.env.GOOGLE_PRIVATE_KEY, GOOGLE_APPLICATION_CREDENTIALS_JSON: process.env.GOOGLE_APPLICATION_CREDENTIALS_JSON
    }
};

export default nextConfig;